# Generated by Django 5.2 on 2025-04-24 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('theme', models.CharField(max_length=1000)),
                ('learning_objective', models.TextField()),
                ('student_characteristics', models.TextField(help_text="Beyond what was entered in each student's profile.")),
                ('number_of_lessons', models.IntegerField()),
                ('length_of_session', models.IntegerField(help_text='in minutes')),
                ('students', models.ManyToManyField(to='tutor.student')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
