# Generated by Django 5.2 on 2025-04-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_rename_class_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='student_characteristics',
            field=models.TextField(blank=True, help_text="Beyond what was entered in each student's profile.", null=True),
        ),
    ]
