# Generated by Django 5.2 on 2025-04-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_section_student_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='syllabus',
            field=models.TextField(blank=True, null=True),
        ),
    ]
