# Generated by Django 5.2 on 2025-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_section_syllabus'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='frameworks',
            field=models.TextField(blank=True, null=True, verbose_name='Are there any specific standards or frameworks you need to align with (e.g., Common Core, state standards, professional competencies)?'),
        ),
        migrations.AddField(
            model_name='section',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='What are the main course goals or key concepts you want students to master?'),
        ),
        migrations.AddField(
            model_name='section',
            name='level',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='What is the academic level (e.g., K-12 grade level, undergraduate, graduate)?'),
        ),
        migrations.AddField(
            model_name='section',
            name='subject',
            field=models.CharField(blank=True, max_length=2000, null=True, verbose_name='What subject/discipline is this course in?'),
        ),
        migrations.AlterField(
            model_name='section',
            name='learning_objective',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='theme',
            field=models.CharField(max_length=1000, verbose_name='Course Topic'),
        ),
    ]
