# Generated by Django 5.2 on 2025-04-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_section_frameworks_section_goals_section_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AddField(
            model_name='student',
            name='weak_areas',
            field=models.TextField(blank=True, null=True, verbose_name='Identified Weak Areas'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Course Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_grades',
            field=models.TextField(blank=True, null=True, verbose_name='Current Grade Level'),
        ),
        migrations.AlterField(
            model_name='student',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Goal & Expectations for Tutors'),
        ),
    ]
