# Generated by Django 5.2 on 2025-05-01 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_alter_section_options_student_weak_areas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=500)),
                ('topic', models.CharField(max_length=1000)),
                ('grade_level', models.CharField(max_length=300)),
                ('duration', models.IntegerField(help_text='in minutes')),
                ('objectives', models.TextField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('other_details', models.TextField(blank=True, null=True)),
                ('lesson_plan', models.TextField(blank=True, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='tutor.section')),
            ],
        ),
    ]
