# Generated by Django 5.2 on 2025-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.URLField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(help_text='in minutes', verbose_name='Lesson Duration'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='materials',
            field=models.TextField(blank=True, null=True, verbose_name='What materials (if any) do you want to use?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Name of the Lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='objectives',
            field=models.TextField(blank=True, null=True, verbose_name='What are the objectives for this lesson?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='other_details',
            field=models.TextField(blank=True, null=True, verbose_name='Any other details about the lesson?'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='topic',
            field=models.CharField(max_length=1000, verbose_name='Topic of Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, to='tutor.resource'),
        ),
        migrations.AddField(
            model_name='section',
            name='resources',
            field=models.ManyToManyField(blank=True, null=True, to='tutor.resource'),
        ),
    ]
