# Generated by Django 5.2 on 2025-05-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_resource_alter_lesson_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='resources',
            field=models.ManyToManyField(blank=True, to='tutor.resource'),
        ),
        migrations.AlterField(
            model_name='section',
            name='resources',
            field=models.ManyToManyField(blank=True, to='tutor.resource'),
        ),
    ]
