# Generated by Django 5.2 on 2025-05-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_alter_lesson_resources_alter_section_resources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='section',
            name='resources',
        ),
        migrations.AddField(
            model_name='resource',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.lesson'),
        ),
        migrations.AddField(
            model_name='resource',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutor.section'),
        ),
        migrations.AlterField(
            model_name='student',
            name='goals',
            field=models.TextField(blank=True, null=True, verbose_name='Goal & Expectations'),
        ),
    ]
