# Generated by Django 5.1.4 on 2025-04-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='why',
            field=models.TextField(blank=True, null=True, verbose_name='Why are you learning another language?'),
        ),
    ]
