# Generated by Django 5.1.4 on 2025-04-02 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_why'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='display_motivation',
            field=models.BooleanField(default=True, verbose_name='Display motivational elements on the homepage?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_reminder_email',
            field=models.BooleanField(default=False),
        ),
    ]
