# Generated by Django 5.2 on 2025-04-24 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_display_motivation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='display_motivation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='send_reminder_email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='why',
        ),
    ]
