# Generated by Django 5.2 on 2025-04-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_display_motivation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subjects_taught',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tools_available',
            field=models.TextField(blank=True, help_text='Zoom, Google Meet, etc', null=True),
        ),
    ]
